---
- import_tasks: darwin.yml
  when:
    - ansible_system == 'Darwin'
    - cabal_download_url is not defined

- name: Define cabal_download_url (Linux)
  set_fact:
    cabal_download_url: "{{ __cabal_base_url }}/cabal-install-{{ cabal_version }}-{{ ansible_architecture }}-unknown-linux.tar.xz"
  when:
    - ansible_system == 'Linux'
    - cabal_download_url is not defined

- name: Download cabal
  get_url:
    url: "{{ cabal_download_url }}"
    dest: "{{ workspace }}/cabal-install-{{ cabal_version }}.tar.xz"

- name: Create extract directory
  file:
    path: "{{ workspace }}/cabal-install-{{ cabal_version }}"
    state: directory
    mode: 0755

- name: Extract cabal
  unarchive:
    src: "{{ workspace }}/cabal-install-{{ cabal_version }}.tar.xz"
    dest: "{{ workspace }}/cabal-install-{{ cabal_version }}/"
    mode: 0755
    remote_src: true

- name: Copy binary
  copy:
    src: "{{ workspace }}/cabal-install-{{ cabal_version }}/cabal"
    dest: "{{ cabal_install_dir }}/cabal"
    mode: 0755
    remote_src: true
