---
- name: Define cabal_download_url
  set_fact:
    cabal_download_url: "{{ cabal_base_url }}/cabal-install-{{ cabal_version }}-{{ ansible_architecture }}-unknown-linux.tar.xz"
  when: ansible_system == 'Linux'

- name: Download cabal
  get_url:
    url: "{{ cabal_download_url }}"
    dest: "{{ workspace }}/cabal-install-{{ cabal_version }}.tar.xz"

- name: Create extract directory
  file:
    path: "{{ workspace }}/cabal-install-{{ cabal_version }}"
    state: directory
    mode: 0755

- name: Extract cabal
  unarchive:
    src: "{{ workspace }}/cabal-install-{{ cabal_version }}.tar.xz"
    mode: 0755
    remote_src: true

- name: Copy binary
  copy:
    src: "{{ workspace }}/cabal-install-{{ cabal_version }}/cabal"
    dest: /usr/local/bin/cabal
    mode: 0755
    remote_src: true
