---
- name: ansible_kernel_version
  debug:
    msg: "{{ ansible_kernel_version }}"

- name: ansible_distribution_release
  debug:
    msg: "{{ ansible_distribution_release }}"

- name: ansible_distribution_version
  debug:
    msg: "{{ ansible_distribution_version }}"

- name: Define cabal_download_url (Darwin)
  set_fact:
    cabal_download_url: "{{ cabal_base_url }}/cabal-install-{{ cabal_version }}-{{ ansible_architecture }}-apple-darwin17.7.0.tar.xz"
  when: ansible_system == 'Darwin'

- name: Define cabal_download_url (Linux)
  set_fact:
    cabal_download_url: "{{ cabal_base_url }}/cabal-install-{{ cabal_version }}-{{ ansible_architecture }}-unknown-linux.tar.xz"
  when: ansible_system == 'Linux'

- name: Download cabal
  get_url:
    url: "{{ cabal_download_url }}"
    dest: "{{ workspace }}/cabal-install-{{ cabal_version }}.tar.xz"

- name: Create extract directory
  file:
    path: "{{ workspace }}/cabal-install-{{ cabal_version }}"
    state: directory
    mode: 0755

- name: Extract cabal
  unarchive:
    src: "{{ workspace }}/cabal-install-{{ cabal_version }}.tar.xz"
    dest: "{{ workspace }}/cabal-install-{{ cabal_version }}/"
    mode: 0755
    remote_src: true

- name: Copy binary
  copy:
    src: "{{ workspace }}/cabal-install-{{ cabal_version }}/cabal"
    dest: /usr/local/bin/cabal
    mode: 0755
    remote_src: true
