---
- name: Verify
  hosts: all
  tasks:
    - name: Get cabal version # noqa 301
      command: /usr/local/bin/cabal --version
      register: result
    - name: Check cabal version
      assert:
        that: "'3.2.0.0' in result.stdout"
