---
name: Darwin

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: brew install gnu-tar
      - run: python -m pip install -r requirements.txt
      - run: mol test -s darwin
