---
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python_version: 3.x
      - run: python -m pip install -r requirements.txt
      - run: mol test
